### Récupérer tous les quizzes
http://127.0.0.1:8000/api/quizzes/
Accept: application/json
### Récupérer tous les quizzes
http://127.0.0.1:8000/api/leaderboard/
Accept: application/json

### Récupérer un quiz par ID
GET http://127.0.0.1:8000/api/quizzes/1/
Accept: application/json

### Créer un quiz (exemple POST)
POST http://127.0.0.1:8000/api/quizzes/
Content-Type: application/json

{
  "titre": "Comment réduire la dépendance numérique à l'école ?",
  "contenu": "Choisissez la bonne réponse pour progresser dans la démarche NIRD",
  "categorie": 1,
  "reponses": [
    { "texte": "Organiser des activités hors écran", "est_correct": true, "ordre": 1 },
    { "texte": "Augmenter le temps d'écran", "est_correct": false, "ordre": 2 },
    { "texte": "Ignorer le problème", "est_correct": false, "ordre": 3 }
  ]
}

### Mettre à jour un quiz (PUT)
PUT http://127.0.0.1:8000/api/quizzes/1/
Content-Type: application/json

{
  "titre": "Mise à jour du quiz NIRD",
  "contenu": "Nouvelle description",
  "categorie": 1
}

### Supprimer un quiz
DELETE http://127.0.0.1:8000/api/quizzes/1/


### Supprimer un quiz
GET http://127.0.0.1:8000/api/categories-count/


### Supprimer un quiz

POST http://127.0.0.1:8000/api/verifier-reponse/
Content-Type: application/json
Authorization: Token <>


### Supprimer un quiz
POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
  "username": "11TT11",
  "email": "111@gmail.com",
  "password": "1111111@"
}

### 

# 1️⃣ Login utilisateur pour obtenir le token
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
  "username": "nesibe2",
  "password": "491200@"
}

### 

# 2️⃣ Vérifier une réponse de quiz (authentifié)
POST http://api.tm-code.online/api/verifierreponse/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0OTEyMDQ1LCJpYXQiOjE3NjQ5MTAyNDUsImp0aSI6IjBiMTllMmQwMWMxYjQ2MzBiOGU4NTgzZmIxNjFlNWIyIiwidXNlcl9pZCI6IjkifQ.5PQkJzxMkkpLfv-R-j20cjIp7y1pn0hicT5TjP4vdDE

{
  "reponse_id": 133
}

###

http://127.0.0.1:8000/api/informations/
Accept: application/json
### Récupérer tous les quizzes