# Generated by Django 5.2.8 on 2025-12-05 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0002_categorie_profile_level_information_quiz_reponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AUTH.quiz')),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AUTH.reponse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AUTH.profile')),
            ],
            options={
                'unique_together': {('user', 'quiz')},
            },
        ),
    ]
